### ISSUE TITLE
App is using "Combine" instead of "replace" with frames

### ISSUE THREAD

**Issue by YayTheReal** [Malpp/DiscordGifSplitter#12]
This results in the previus frame elements remaining where the background is transparent. As far as I know, this could be easily fixed.

**Comment by Malpp** [comment]
Could you provide me with a test case so I can figure this out?

**Comment by Malpp** [comment]
Ok, I've found an example of this happening

![mmddo5aac6](https://user-images.githubusercontent.com/17149559/50544983-9575ac00-0bd4-11e9-90ee-36030cbc7666.gif)

**Comment by Malpp** [comment]
Oh wow this problem was fun. FFmpeg was the cause all along. So [this](https://trac.ffmpeg.org/ticket/6813#no2) ticket was put in 7 months ago and the issue was fixed 2 weeks ago. So the solution would be to use the nightly build of FFmpeg from [here](https://ffmpeg.zeranoe.com/builds/), or this [one](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20181229-fccba32-win64-static.zip)

**Comment by YayTheReal** [comment]
> 
> 
> Oh wow this problem was fun. FFmpeg was the cause all along. So [this](https://trac.ffmpeg.org/ticket/6813#no2) ticket was put in 7 months ago and the issue was fixed 2 weeks ago. So the solution would be to use the nightly build of FFmpeg from [here](https://ffmpeg.zeranoe.com/builds/), or this [one](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20181229-fccba32-win64-static.zip)
